/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/earth.glb -t 
Author: BamPistache (https://sketchfab.com/karinkreeft8)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/earth-0caafb7e837047a688a3e504c0ea74af
Title: Earth
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    earth4_blinn1_0: THREE.Mesh
    earth4_lambert1_0: THREE.Mesh
  }
  materials: {
    blinn1: THREE.MeshStandardMaterial
    lambert1: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Earth(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/earth.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.earth4_blinn1_0.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.earth4_lambert1_0.geometry} material={materials.lambert1} />
    </group>
  )
}

useGLTF.preload('/earth.glb')
